name: Live TV SD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '45 3,7,11,15,19,23 * * *'  # Run every 4 hours
  workflow_dispatch:      # Enable manual triggering

jobs:
  generate_m3u:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create en Folder
        run: mkdir -p en     

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install necessary packages
        run: |
          sudo apt-get update    
          sudo apt-get install -y unzip wget libgconf-2-4 libnss-wrapper gconf2-common libxcb-xinerama0
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          rm google-chrome-stable_current_amd64.deb
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas webdriver-manager selenium selenium_stealth pytz

      - name: Run Python Script livetv
        run: |
          python py/tvsd.py > en/tvsd.m3u         

      # Extract the token from one of the other links
      - name: Extract Token and Update ESPN Links
        run: |
          # Extract the token from the first channel in livetv.m3u
          token=$(grep -oP '(?<=token=)[^"]*' en/tvsd.m3u | tail -1)

          # Update the ESPN and ESPN2 links with the extracted token
          sed -i "/tvg-name=\"ESPN\"/{n;s|hhttps://raw.githubusercontent.com/buhtigd1/TVSD/main/off/offline.mp4|https://v6.thetvapp.to/hls/ESPN/index.m3u8?token=$token|g}" en/tvsd.m3u
          sed -i "/tvg-name=\"ESPN2\"/{n;s|https://raw.githubusercontent.com/buhtigd1/TVSD/main/off/offline.mp4|https://v6.thetvapp.to/hls/ESPN2/index.m3u8?token=$token|g}" en/tvsd.m3u

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update token"
          branch: main
          file_pattern: en/tvsd.m3u
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
