name: Live EPG

on:
  schedule:
    - cron: '0 1 * * *'  # Run at 1am everyday
  workflow_dispatch:

jobs:
  scrape_and_generate_epg:
    name: Scrape TV Programming and Generate EPG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz

      - name: Run EPG Script
        run: |
          python py/tvsdxml.py --days 3 > en/tvsd.xml
        env:
          TZ: America/New_York  # Set the timezone

      - name: Compress XML with gzip (retain original)
        run: |
          gzip -c en/tvsd.xml > en/tvsd.xml.gz

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update token"
          branch: main
          file_pattern: en/tvsd.xml en/tvsd.xml.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
